name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  test:
    name: SimonDrivesTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Install Modules
      run: |
          npm i mqtt --save
          npm i -D electron@latest
          npm i dialogs --save
    - name: Test
      run: node/ npm start 
